version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: desent-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: desent
      POSTGRES_PASSWORD: desent123
      POSTGRES_DB: desent_pretest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
